name: Backend Master Staging Deploy

on:
  push:
    branches: [master]
    paths:
      - "packages/backend/**"

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Staging Heroku aka culdevateapistaging
        run: |
          git push --force https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_STAGING_API_NAME }}.git `git subtree split --prefix packages/backend/ HEAD`:master
